config/routes.rb
Rails.application.routes.draw do
  # https://stackoverflow.com/questions/65794152/how-can-i-do-a-health-check-for-a-rails-based-app-on-render
  get '/health_check', to: proc { [200, {}, ['success']] }
  # whereas below from railsguide3.13 doesnt work
  # get '/health', to: ->(env) { [204, {}, ['']] }

  scope module: :public_pages do
    root 'home#welcome'
    get '/about', to: 'footer#about'
    get '/terms_and_conditions', to: 'footer#package_policy'
    get '/charges_and_deductions', to: 'footer#charges'
    get '/privacy_policy',  to: 'footer#privacy_policy'
    get '/payment_policy',  to: 'footer#payment_policy'
    get '/contact',  to: 'footer#contact'
    get '/group_classes', to: 'home#group_classes'
    get '/signup', to: 'home#signup'
    post '/signup',  to: 'home#create_account'
    get '/chootiya', to: 'home#wedontsupport'
    get '/buboo', to: 'home#hearts'
  end

  # https://guides.rubyonrails.org/routing.html 2.10 Adding More RESTful Actions...2.10.2 Adding Collection Routes
  scope module: :admin do
    get '/wkclasses/instructor_select'
    get '/footfall', to: 'bookings#footfall'
    get '/timetable', to: 'timetables#public_format', as: 'public_format_timetable'
    post '/timetable/:id/copy', to: 'timetables#deep_copy', as: 'timetable_deep_copy'
    post '/wkclasses/:id/repeat', to: 'wkclasses#repeat', as: 'wkclass_repeat'
    resources :products, :wkclasses, :workouts do
      # get 'filter', on: :collection
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
    # Something to be aware of https://guides.rubyonrails.org/routing.html section 2.2
    # if say get 'admin/purchases/filter' was after the (admin namespaced) resources :purchases, a request to admin/purchases/filter would be handled by the show method
    # of the purchases controller (with params[:id] = 'filter') and an error would arise 'ActiveRecord::RecordNotFound (Couldn't find Purchase with 'id'=filter):'. 
    # the first match of the url 'admin/purchases/filter' would be /admin/purchases/:id(.:format), handled by the show method. The admin/purchases/filter(.:format) would be ignored as it comes later. 
    resources :purchases do
      collection do
        get 'clear_filters'
        get 'client_filter'
        get 'discount'
        get 'filter'
        get 'form_field_change'
        get 'analysis'
        patch ':id/expire', to: 'purchases#expire', as: 'expire'
      end
    end
    resources :clients do
      collection do
        get 'filter'
        get 'clear_filters'
        get 'analyze'        
      end
    end
    resources :freezes, except: [:show] do
      get 'filter', on: :collection
    end
    resources :workout_groups do
      collection do
        get ':id/instructor_expense_filter', to: 'workout_groups#instructor_expense_filter', as: 'instructor_expense_filter'
        get ':id/show_workouts', to: 'workout_groups#show_workouts', as: 'show_workouts'
        patch 'toggle_current/:id', to: 'workout_groups#toggle_current', as: 'toggle_current'
      end
    end
    resources :adjustments, :entries, :prices, except: [:index, :show]
    resources :accounts, only: [:create, :update, :destroy]
    resources :achievements, except: [:show]    
    # an update of a booking is handled by the booking cancellations controller (not the bookings controller)
    resources :bookings, only: [:new, :create, :destroy]
    resources :booking_cancellations, only: :update
    resources :fitternities, :instructors, :partners, :timetables
    resources :restarts, except: :show
    resources :table_times, :table_days, except: [:index, :show]
  end

  namespace :superadmin do
    resource :settings, only: [:show, :create]
  end
  
  # https://guides.rubyonrails.org/routing.html section 2.6 namespaces & routing
  # routes to a superadmin namespaced controller, but doesn't include superadmin in the url or url helper
  scope module: :superadmin do
    resources :announcements do
      collection do
        get 'add_client/:id', to: 'announcements#add_client', as: 'add_client'
        get ':id/remove_client/:client_id', to: 'announcements#remove_client', as: 'remove_client'
        get ':id/blast_off', to: 'announcements#blast_off', as: 'blast_off'
        get 'clear_filters/:id', to: 'announcements#clear_filters', as: 'clear_filters'
        get 'filter/:id', to: 'announcements#filter', as: 'filter_client'
        delete 'destroy_notification/:id', to: 'announcements#destroy_notification', as: 'destroy_notification'
      end
    end
    post 'orders', to: 'orders#create'
    post 'verify_payment', to: 'orders#verify_payment'
    post 'regular_expenses/add'
    namespace :charts do
      get 'purchase_count_by_week'
      get 'purchase_charge_by_week'
      # get 'purchase_count_by_wg/:year', to: '#purchase_count_by_wg', as: :purchase_count_by_wg
      get 'purchase_count_by_wg'
      get 'purchase_charge_by_wg'
      get 'product_group_count'
      get 'product_pt_count'
    end
    resource :blast, only: :show do
      collection do
        get 'add_client'
        get 'remove_client/:id', to: 'blasts#remove_client', as: 'remove_client'
        get 'blast_off'
        get 'clear_filters'
        get 'filter'
        get 'test'
        post 'add_message'
      end
    end
    resource :bulk_freeze, only: :show do
      collection do
        get 'remove_purchase/:id', to: 'bulk_freezes#remove_purchase', as: 'remove_purchase'
        get 'blast_off'
        get 'clear_filters'
        get 'filter'
        post 'process_details'        
      end
    end
    resources :discounts, :discount_reasons
    resources :employee_accounts do
      collection do
        get 'add_role/:id', to: 'employee_accounts#add_role', as: 'add_role'
        get 'remove_role/:id', to: 'employee_accounts#remove_role', as: 'remove_role'
        patch 'password_reset_of_employee/:id', to: 'employee_accounts#password_reset_of_employee', as: 'password_reset'
      end
    end
    resources :instructor_rates, :other_services, :regular_expenses, except: [:show]
    resources :payments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
    resources :expenses, except: :show do
      get 'filter', on: :collection
    end
  end

  scope module: :auth do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    get '/switch_account_role', to: 'sessions#switch_account_role'
    # hack to simulate closing a browser used only for integration testing (as sessions can't be directly amended in integration tests)
    get '/close_the_browser',  to: 'sessions#close_the_browser'
  end

  scope module: :client do
    get 'profile/:id', to: 'data_pages#profile', as: :client_profile
  end

  namespace :client do    
    get '/:id/notifications', to: 'data_pages#notifications', as: 'notifications'
    get '/:id/shop', to: 'dynamic_pages#shop', as: 'shop'
    get '/:id/history', to: 'data_pages#history', as: 'history'
    get ':id/bookings', to: 'bookings#index', as: 'bookings'
    post ':id/bookings', to: 'bookings#create', as: 'create_booking'
    # temporarily retain this route and redirect to client_bookings_path
    get '/:id/book', to: 'dynamic_pages#book', as: 'book'
    get '/:id/pt', to: 'data_pages#pt', as: 'pt'
    get '/timetable', to: 'data_pages#timetable', as: 'timetable'
    get '/:id/achievements', to: 'data_pages#achievements', as: 'achievements'
    get ':id/new_freeze', to: 'package_modification#new_freeze', as: 'package_modification_new_freeze'
    get ':id/restart', to: 'package_modification#restart', as: 'package_modification_restart'
    get ':id/transfer', to: 'package_modification#transfer', as: 'package_modification_transfer'
    get ':id/cancel_freeze', to: 'package_modification#cancel_freeze', as: 'package_modification_cancel_freeze'
    get ':id/cancel_restart', to: 'package_modification#cancel_restart', as: 'package_modification_cancel_restart'
    get ':id/cancel_transfer', to: 'package_modification#cancel_transfer', as: 'package_modification_cancel_transfer'
    post ':id/buy_freeze', to: 'package_modification#buy_freeze', as: 'buy_freeze'
    # test out on console $app.client_update_booking_path(Client.first, Client.first.bookings.last)
    # => "/client/1/booking_cancellations/1668"
    patch ':client_id/booking_cancellations/:id', to: 'booking_cancellations#update', as: 'update_booking' 
    resources :waitings, only: [:create, :destroy]
    resources :password_resets, only: [:new, :create, :edit, :update] do
      collection do
        # TODO: should be patch
        get 'password_change/:id', to: 'password_resets#password_change', as: 'password_change'
      end
    end
  end

  scope module: :shared do
    # resources :achievements, except: [:show]
    resources :body_markers, :strength_markers, except: [:show] do
      get 'filter', on: :collection
    end
    resources :challenges
    resources :client, only: [] do # already have the client resource routes in the admin module, dont want an extra set handled by a shared/clients controller
      # the declaration is created from a form scoped to an exisiting client, so the form defaults to a patch (update request) (with nested attributes for  the new declaration)
      # so we only have an update route, not a create route
      # we cannot edit or destroy declarations through the UI
      resource :declaration, only: [:new, :show, :update] do
        resources :declaration_updates, except: [:index] 
      end
    end
    resources :declarations, only: [:index] do # we want an index of all declarations (not an index of each clients declarations)  
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
  end
end

app/controllers/superadmin/announcements_controller.rb
class Superadmin::AnnouncementsController < Superadmin::BaseController
  before_action :set_announcement, only: %i[ show edit update destroy filter clear_filters blast_off remove_client add_client ]

  def index
    @announcements = Announcement.order_by_created_at
  end

  def show
    @recipients = Client.all
    handle_filter
    @addable_clients = Client.exclude(@recipients).order_by_first_name
    set_individually_selected_clients
    @recipient_list_size = @recipients.size
    @pagy_recipients, @recipients = pagy(@recipients, items: Rails.application.config_for(:constants)['recipient_pagination'])
    # https://ddnexus.github.io/pagy/docs/how-to/ Customize the page param
    @pagy_notifieds, @notifieds = pagy(@announcement.clients,  page_param: :notified_page, items: Rails.application.config_for(:constants)['recipient_pagination'])
  end

  def new
    @announcement = Announcement.new
  end

  def edit
  end

  def create
    @announcement = Announcement.new(announcement_params)
    if @announcement.save
      flash[:success] = t('.success')
      redirect_to announcements_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @announcement.update(announcement_params)
      flash[:success] = t('.success')
      redirect_to announcements_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @announcement.destroy
    flash[:success] = t('.success')
    redirect_to announcements_path
  end

  def destroy_notification
    notification = Notification.find(params[:id])
    announcement = notification.announcement
    notification.destroy
    flash[:success] = t('.success')
    redirect_to announcement_path(announcement)    
  end

  def filter
    clear_session(:filter_announcement_packagee, :filter_announcement_group_packagee, :filter_announcement_group_packagee_not_rider,
                  :filter_announcement_has_booking_today, :filter_announcement_has_booking_tomorrow, :filter_announcement_has_booking_in_future,
                  :filter_announcement_nobody)
    set_announcement_session(:packagee, :group_packagee, :group_packagee_not_rider, :has_booking_today, :has_booking_tomorrow, :has_booking_in_future, :nobody)
    redirect_to announcement_path(@announcement)
  end

  def clear_filters
    clear_session(:filter_announcement_packagee,
                  :filter_announcement_group_packagee,
                  :filter_announcement_group_packagee_not_rider,
                  :filter_announcement_has_booking_today,
                  :filter_announcement_has_booking_tomorrow,
                  :filter_announcement_has_booking_in_future,
                  :filter_announcement_nobody,
                  :announcement_client_ids_add, :announcement_client_ids_remove)
    redirect_to announcement_path(@announcement)
  end

  def blast_off
    @recipients = Client.all
    handle_filter
    @recipients -= @announcement.clients
    passes = 0
    errors = 0
    # add_greeting = session[:greeting] == '1' ? true : false 
    @recipients.each do |recipient|
      # recipient_name = add_greeting ? recipient.first_name : nil
      account = recipient.account
      @announcement.notifications.create(account_id: account.id)
      passes += 1
    rescue
      next
      errros += 1
    end
    flash[:success] = t('.success', errors: ActionController::Base.helpers.pluralize(errors, "announcement"), passes: ActionController::Base.helpers.pluralize(passes, "announcement"))
    redirect_to announcement_path(@announcement)
  end  

  def remove_client
    client_id = params[:client_id]
    session[:announcement_client_ids_remove] = client_ids_remove << client_id
    session[:announcement_client_ids_add].delete(client_id)
    redirect_to announcement_path(@announcement)
  end

  def add_client
    client_id = params[:client_id]
    session[:announcement_client_ids_add] = client_ids_add << client_id
    session[:announcement_client_ids_remove].delete(client_id)
    redirect_to announcement_path(@announcement)
  end  

  private

  def client_ids_add
    session[:announcement_client_ids_add] ||= []
  end
  
  def client_ids_remove
    session[:announcement_client_ids_remove] ||= []
  end

  def handle_filter
    %w[packagee group_packagee group_packagee_not_rider has_booking_today has_booking_tomorrow has_booking_in_future nobody].each do |key|
      @recipients = @recipients.send(key) if session["filter_announcement_#{key}"].present?
    end
    unless client_ids_add.empty?
      ids = (client_ids_add + @recipients.unscope(:order).pluck(:id)).uniq
      @recipients = Client.where(id: ids).order_by_first_name
    end
    @recipients = @recipients.where.not(id: @announcement.clients).order_by_first_name
    @recipients = @recipients.where.not(id: client_ids_remove).order_by_first_name
  end

  def set_individually_selected_clients
    @excluded_clients = Client.where(id: client_ids_remove)
    @added_clients = Client.where(id: client_ids_add)    
  end

  #TODO: make dry - see set_session in sessions_helper.rb
  def set_announcement_session(*args)
    args.each do |session_key|
      session["filter_announcement_#{session_key}"] = params[session_key] || session["filter_announcement_#{session_key}"]
    end
  end      

  # Use callbacks to share common setup or constraints between actions.
  def set_announcement
    @announcement = Announcement.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def announcement_params
    # params.fetch(:announcement, {})
    params.require(:announcement).permit(:message)
  end
end

app/controllers/superadmin/base_controller.rb
class Superadmin::BaseController < ApplicationController
  layout 'admin'
  before_action :superadmin_account
  before_action :set_public_timetable # for navigation bar
  before_action :set_admin_status

  private

  def set_public_timetable
    @current_timetable = Timetable.actives_at(Time.zone.now).first    
  end
end

app/controllers/superadmin/other_services_controller.rb
class Superadmin::OtherServicesController < Superadmin::BaseController
  before_action :set_other_service, only: [:edit, :update, :destroy]

  def index
    @other_services = OtherService.all
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def new
    @other_service = OtherService.new
  end

  def edit; end

  def create
    @other_service = OtherService.new(other_service_params)
    if @other_service.save
      redirect_to other_services_path
      flash[:success] = t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @other_service.update(other_service_params)
      redirect_to other_services_path
      flash[:success] = t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @other_service.destroy
    redirect_to other_services_path
    flash[:success] = t('.success')
  end

  private

  def set_other_service
    @other_service = OtherService.find(params[:id])
  end

  def other_service_params
    params.require(:other_service).permit(:name, :link)
  end
end

app/helpers/superadmin/bulk_freezes_helper.rb
module Superadmin::BulkFreezesHelper
  def processed_message
    "'#{@note}' freeze scheduled for #{duration} #{period}"
  end

  def duration
    days = (@start_date..@end_date).count
    ActionController::Base.helpers.pluralize(days, 'day')
  end

  def period
    "#{Date.parse(@start_date).strftime('%-d %B %Y')} to #{Date.parse(@end_date).strftime('%-d %B %Y')}"
  end
end

app/views/superadmin/payments/_download.html.erb
<div class="container px-1">  
  <p>
    Download:
    <%#= link_to "Full Data", payments_path(format: "csv", export_all: true) %> |
    <%= link_to "Accountant Data", payments_path(format: "xls", export_all: true) %>
  </p>
</div>

app/views/superadmin/payments/_filter_form.html.erb
<div id="payments-filter" class="container px-1 mb-5">
  <div class="container search">
    <%= render partial: 'sort_selection' %>
    <hr class = "search mb-3"></hr>
    <%= form_with(url: filter_payments_path, method: "get", class: "form-class", data: {turbo_frame: "payments"}) do %>
      <div class="container mb-1">
        <div class="row">
          <div class="col-4 px-0">
            <fieldset>
              <legend>TYPE</legend>
              <% @payable_types.each do |payable_type| %>
                <%= label_tag nil, class: "chbox-lbl-filters" do %>
                  <%= check_box_tag 'payable_types[]', payable_type, session[:filter_payable_types].present? ? session[:filter_payable_types].include?(payable_type) : false, class: "checkbox-class", id: "chbox#{payable_type}", onchange: "this.form.requestSubmit()"  %>
                  <%= payable_type %>
                <% end %>
              <% end %>
            </fieldset>
          </div>
          <div class="col-4 px-0">   
            <fieldset>       
              <legend>ATTRIBUTE</legend>
                <% @other_attributes.each do |attribute| %>
                  <%= label_tag nil, class: "chbox-lbl-filters" do %>
                    <%= check_box_tag attribute, attribute, session["filter_#{attribute}"].present? ? true : false, class: "checkbox-class", id: "chbox#{attribute}", onchange: "this.form.requestSubmit()"  %>
                    <%= attribute.split('_').join(' ') %>
                  <% end %>
                <% end %>
            </fieldset>
          </div>

          <div class="container d-flex">
            <%= link_to image_tag('clear_filter.png', class: "button_icon"), clear_filters_payments_path, {class: "search searchdelete icon-container"} %>
          </div>

          <fieldset class="mt-2" style="margin-left:-1.3rem">
            <select name="payments_period" class= "sort" onchange="this.form.requestSubmit()">
              <%= options_for_select @months, session[:payments_period] %>
            </select>
          </fieldset>
        </div>
      </div>
    <% end %>
    <hr class = "search mb-3"></hr>
  </div>
</div>

app/views/superadmin/payments/_form.html.erb
<div class="field"> 
  <%= form_with(model: payment, class: 'admin_form my-2', data: {turbo: false}) do |form| %>
    <%= turbo_frame_tag 'errors' do %>  
      <% if payment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>
          <ul>
            <% payment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>

    <div class="field">
      <%= form.label :amount %>
      <%= form.number_field :amount %>
    </div>

    <div class="field">
      <%= form.label :dop, 'Date of purchase' %>
      <%= form.date_select :dop %>
    </div>

    <div class="field">
      <%= form.label :payment_mode %>
      <%= form.select :payment_mode, options_for_select(@payment_methods, @payment.payment_mode), include_blank: true %>
    </div>

    <div class="field">
      <%= form.label :note %>
      <%= form.text_area :note, cols: 40, rows: 5 %>
    </div>  

    <div class="actions">
      <%= form.submit %>
    </div>

    <div class="cancel">
      <%= link_to image_tag('delete.png', class: "table_icon"), payments_path %>
    </div>  
  <% end %>
</div>

app/views/superadmin/payments/_payment.html.erb
<%= turbo_frame_tag payment do %>
  <div class="row">
    <% purchase = payment.purchase %>
    <div class="column col-1x"><%= purchase.client.name %></div>
    <div class="column col-1x"><%= payment.dop.strftime('%d %b %y') %></div>
    <div class="column col-1x"><%= link_to payment.payable_type, purchase_path(purchase), class: "like_button", data: {turbo: false} %></div>
    <div class="column col-1x"><%= rupees(payment.amount) %></div>
    <div class="column col-1x nomobile"><%= payment.payment_mode %></div>
    <div class="column nomobile"><%= payment.online? ? raw("&check;") : "-" %></div>
    <div class="column col-1x nomobile"><%= payment.note %></div>
    <div class="column nomobile"><%= link_to image_tag('edit.png', class: 'table_icon'), edit_payment_path(payment) %></div>
  </div>
<% end %>

app/views/superadmin/payments/_payments_table.html.erb
<div id="payments-table" class="container px-0 mb-5">
  <div class="page_entries_info px-1">
    <% if @superadmin_plus %>
      <div class="record-count mb-1">
        <%= "showing #{@payments&.length} of #{@pagy&.count}" %>
      </div>
    <% end %>
    <div data-controller="pagy-initializer">
      <%== pagy_bootstrap_combo_nav_js(@pagy) %>
    </div>   
  </div>
  <div class="mt-2">
    <% if @superadmin_plus %>
      <div class="px-1 mb-1"><%= rupees(@payments_amount_sum) %><small> (all pages)</small></div>
    <% end %>  
    <div class="text-uppercase fst-italic">Payments<small><%= "(#{@payments.size})" %> </small></div>
  </div>
  <div class="admin-table mt-2">
    <div class="row fw-bolder">
      <div class="column col-1x">Client</div>
      <div class="column col-1x">Date</div>        
      <div class="column col-1x">Type</div>        
      <div class="column col-1x">Amount</div>
      <div class="column col-1x nomobile">Mode</div>        
      <div class="column nomobile">Web</div>        
      <div class="column col-1x nomobile">Note</div>
      <div class="column nomobile"></div>
    </div>
  </div>
  <div class="admin-table striped">
    <%= render partial: @payments %>
  </div>
</div>

app/views/superadmin/payments/_sort_selection.html.erb
<form action="/payments" method="GET">
  <div class="mt-0">
    <i class="fas fa-sort-alpha-down"></i>
    <select class="form-control-sm mb-2 sort pr-3" name="sort_option" onchange="this.form.requestSubmit()">
      <option disabled="disabled" selected="selected" value="">Sort by</option>
      <option value="client_name" <%="selected" if session[:sort_option] == "client_name"%> >client</option>
      <option value="dop" <%="selected" if session[:sort_option] == "dop"%> >date</option>
    </select>
  </div>
</form>

app/views/superadmin/payments/edit.html.erb
<%= turbo_frame_tag dom_id(@payment) do %>
  <%= render 'form', payment: @payment, class: 'mb-4' %>
<% end %>

app/views/superadmin/payments/index.html.erb
<div class="container px-1">
  <h4>Payments</h4>
</div>
<%= turbo_frame_tag 'payments-and-filter' do %>
  <%= render partial: 'filter_form' %>
  <%= render partial: 'download' %>
  <%= turbo_frame_tag 'payments' do %>
    <%= render partial: 'payments_table' %>
  <% end %>
<% end %>

app/views/superadmin/payments/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="https://www.w3.org/TR/html40/">

  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Client</Data></Cell>
        <Cell><Data ss:Type="String">Date of Payment</Data></Cell>
        <Cell><Data ss:Type="String">Type</Data></Cell>
        <Cell><Data ss:Type="String">Amount</Data></Cell>
        <Cell><Data ss:Type="String">Mode</Data></Cell>
        <Cell><Data ss:Type="String">Note</Data></Cell>
      </Row>
      <% @payments.each do |payment| %>
        <% purchase = payment.purchase %>    
        <Row>
          <Cell><Data ss:Type="String"><%= purchase.client.name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= payment.dop %></Data></Cell>
          <Cell><Data ss:Type="String"><%= payment.payable_type %></Data></Cell>
          <Cell><Data ss:Type="String"><%= payment.amount %></Data></Cell>
          <Cell><Data ss:Type="String"><%= payment.payment_mode %></Data></Cell>
          <Cell><Data ss:Type="String"><%= payment.note %></Data></Cell>
        </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/superadmin/payments/show.html.erb
<div class="admin-table striped mt-2 mb-4">
    <div class="row">
      <div class="column col-1x">Payable</div>
      <div class="column col-2x"><%= @payment.payable_type %></div>
    </div>
    <div class="row">
      <div class="column col-1x">Client</div>
      <div class="column col-2x"><%= @payment.payable.try(:client).try(:name) || @payment.payable.try(:purchase).try(:client).try(:name) || @payment.payable.try(:parent).try(:client).try(:name)  %></div>
    </div>
    <div class="row">
      <div class="column col-1x">Associated Purchase</div>
      <div class="column col-2x"><%= link_to @purchase.product.name, purchase_path(@purchase), class: "like_button" %></div>
    </div>
  <div class="row">
    <div class="column col-1x">Amount</div>
    <div class="column col-2x"><%= rupees(@payment.amount) %></div>
  </div>
  <div class="row">
      <div class="column col-1x">Date of Payment</div>
      <div class="column col-2x"><%= @payment.dop.strftime('%d %b %y') %></div>
    </div>
    <div class="row">
      <div class="column col-1x">Payment mode</div>
      <div class="column col-2x"><%= @payment.payment_mode %></div>
    </div>
    <div class="row">
      <div class="column col-1x">Paid Online</div>
      <div class="column col-2x"><%= @payment.online? ? raw("&check;") : "-" %></div>
    </div>
    <div class="row">
      <div class="column col-1x">Note</div>
      <div class="column col-2x"><%= @payment.note %></div>
    </div>
</div>