config/routes.rb
Rails.application.routes.draw do
  # https://stackoverflow.com/questions/65794152/how-can-i-do-a-health-check-for-a-rails-based-app-on-render
  get '/health_check', to: proc { [200, {}, ['success']] }
  # whereas below from railsguide3.13 doesnt work
  # get '/health', to: ->(env) { [204, {}, ['']] }

  scope module: :public_pages do
    root 'home#welcome'
    get '/about', to: 'footer#about'
    get '/terms_and_conditions', to: 'footer#package_policy'
    get '/charges_and_deductions', to: 'footer#charges'
    get '/privacy_policy',  to: 'footer#privacy_policy'
    get '/payment_policy',  to: 'footer#payment_policy'
    get '/contact',  to: 'footer#contact'
    get '/group_classes', to: 'home#group_classes'
    get '/signup', to: 'home#signup'
    post '/signup',  to: 'home#create_account'
    get '/chootiya', to: 'home#wedontsupport'
    get '/buboo', to: 'home#hearts'
  end

  # https://guides.rubyonrails.org/routing.html 2.10 Adding More RESTful Actions...2.10.2 Adding Collection Routes
  scope module: :admin do
    get '/wkclasses/instructor_select'
    get '/footfall', to: 'bookings#footfall'
    get '/timetable', to: 'timetables#public_format', as: 'public_format_timetable'
    post '/timetable/:id/copy', to: 'timetables#deep_copy', as: 'timetable_deep_copy'
    post '/wkclasses/:id/repeat', to: 'wkclasses#repeat', as: 'wkclass_repeat'
    resources :products, :wkclasses, :workouts do
      # get 'filter', on: :collection
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
    # Something to be aware of https://guides.rubyonrails.org/routing.html section 2.2
    # if say get 'admin/purchases/filter' was after the (admin namespaced) resources :purchases, a request to admin/purchases/filter would be handled by the show method
    # of the purchases controller (with params[:id] = 'filter') and an error would arise 'ActiveRecord::RecordNotFound (Couldn't find Purchase with 'id'=filter):'. 
    # the first match of the url 'admin/purchases/filter' would be /admin/purchases/:id(.:format), handled by the show method. The admin/purchases/filter(.:format) would be ignored as it comes later. 
    resources :purchases do
      collection do
        get 'clear_filters'
        get 'client_filter'
        get 'discount'
        get 'filter'
        get 'form_field_change'
        get 'analysis'
        patch ':id/expire', to: 'purchases#expire', as: 'expire'
      end
    end
    resources :clients do
      collection do
        get 'filter'
        get 'clear_filters'
        get 'analyze'        
      end
    end
    resources :freezes, except: [:show] do
      get 'filter', on: :collection
    end
    resources :workout_groups do
      collection do
        get ':id/instructor_expense_filter', to: 'workout_groups#instructor_expense_filter', as: 'instructor_expense_filter'
        get ':id/show_workouts', to: 'workout_groups#show_workouts', as: 'show_workouts'
        patch 'toggle_current/:id', to: 'workout_groups#toggle_current', as: 'toggle_current'
      end
    end
    resources :adjustments, :entries, :prices, except: [:index, :show]
    resources :accounts, only: [:create, :update, :destroy]
    resources :achievements, except: [:show]    
    # an update of a booking is handled by the booking cancellations controller (not the bookings controller)
    resources :bookings, only: [:new, :create, :destroy]
    resources :booking_cancellations, only: :update
    resources :fitternities, :instructors, :partners, :timetables
    resources :restarts, except: :show
    resources :table_times, :table_days, except: [:index, :show]
  end

  namespace :superadmin do
    resource :settings, only: [:show, :create]
  end
  
  # https://guides.rubyonrails.org/routing.html section 2.6 namespaces & routing
  # routes to a superadmin namespaced controller, but doesn't include superadmin in the url or url helper
  scope module: :superadmin do
    resources :announcements do
      collection do
        get 'add_client/:id', to: 'announcements#add_client', as: 'add_client'
        get ':id/remove_client/:client_id', to: 'announcements#remove_client', as: 'remove_client'
        get ':id/blast_off', to: 'announcements#blast_off', as: 'blast_off'
        get 'clear_filters/:id', to: 'announcements#clear_filters', as: 'clear_filters'
        get 'filter/:id', to: 'announcements#filter', as: 'filter_client'
        delete 'destroy_notification/:id', to: 'announcements#destroy_notification', as: 'destroy_notification'
      end
    end
    post 'orders', to: 'orders#create'
    post 'verify_payment', to: 'orders#verify_payment'
    post 'regular_expenses/add'
    namespace :charts do
      get 'purchase_count_by_week'
      get 'purchase_charge_by_week'
      # get 'purchase_count_by_wg/:year', to: '#purchase_count_by_wg', as: :purchase_count_by_wg
      get 'purchase_count_by_wg'
      get 'purchase_charge_by_wg'
      get 'product_group_count'
      get 'product_pt_count'
    end
    resource :blast, only: :show do
      collection do
        get 'add_client'
        get 'remove_client/:id', to: 'blasts#remove_client', as: 'remove_client'
        get 'blast_off'
        get 'clear_filters'
        get 'filter'
        get 'test'
        post 'add_message'
      end
    end
    resource :bulk_freeze, only: :show do
      collection do
        get 'remove_purchase/:id', to: 'bulk_freezes#remove_purchase', as: 'remove_purchase'
        get 'blast_off'
        get 'clear_filters'
        get 'filter'
        post 'process_details'        
      end
    end
    resources :discounts, :discount_reasons
    resources :employee_accounts do
      collection do
        get 'add_role/:id', to: 'employee_accounts#add_role', as: 'add_role'
        get 'remove_role/:id', to: 'employee_accounts#remove_role', as: 'remove_role'
        patch 'password_reset_of_employee/:id', to: 'employee_accounts#password_reset_of_employee', as: 'password_reset'
      end
    end
    resources :instructor_rates, :other_services, :regular_expenses, except: [:show]
    resources :payments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
    resources :expenses, except: :show do
      get 'filter', on: :collection
    end
  end

  scope module: :auth do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    get '/switch_account_role', to: 'sessions#switch_account_role'
    # hack to simulate closing a browser used only for integration testing (as sessions can't be directly amended in integration tests)
    get '/close_the_browser',  to: 'sessions#close_the_browser'
  end

  scope module: :client do
    get 'profile/:id', to: 'data_pages#profile', as: :client_profile
  end

  namespace :client do    
    get '/:id/notifications', to: 'data_pages#notifications', as: 'notifications'
    get '/:id/shop', to: 'dynamic_pages#shop', as: 'shop'
    get '/:id/history', to: 'data_pages#history', as: 'history'
    get ':id/bookings', to: 'bookings#index', as: 'bookings'
    post ':id/bookings', to: 'bookings#create', as: 'create_booking'
    # temporarily retain this route and redirect to client_bookings_path
    get '/:id/book', to: 'dynamic_pages#book', as: 'book'
    get '/:id/pt', to: 'data_pages#pt', as: 'pt'
    get '/timetable', to: 'data_pages#timetable', as: 'timetable'
    get '/:id/achievements', to: 'data_pages#achievements', as: 'achievements'
    get ':id/new_freeze', to: 'package_modification#new_freeze', as: 'package_modification_new_freeze'
    get ':id/restart', to: 'package_modification#restart', as: 'package_modification_restart'
    get ':id/transfer', to: 'package_modification#transfer', as: 'package_modification_transfer'
    get ':id/cancel_freeze', to: 'package_modification#cancel_freeze', as: 'package_modification_cancel_freeze'
    get ':id/cancel_restart', to: 'package_modification#cancel_restart', as: 'package_modification_cancel_restart'
    get ':id/cancel_transfer', to: 'package_modification#cancel_transfer', as: 'package_modification_cancel_transfer'
    post ':id/buy_freeze', to: 'package_modification#buy_freeze', as: 'buy_freeze'
    # test out on console $app.client_update_booking_path(Client.first, Client.first.bookings.last)
    # => "/client/1/booking_cancellations/1668"
    patch ':client_id/booking_cancellations/:id', to: 'booking_cancellations#update', as: 'update_booking' 
    resources :waitings, only: [:create, :destroy]
    resources :password_resets, only: [:new, :create, :edit, :update] do
      collection do
        # TODO: should be patch
        get 'password_change/:id', to: 'password_resets#password_change', as: 'password_change'
      end
    end
  end

  scope module: :shared do
    # resources :achievements, except: [:show]
    resources :body_markers, :strength_markers, except: [:show] do
      get 'filter', on: :collection
    end
    resources :challenges
    resources :client, only: [] do # already have the client resource routes in the admin module, dont want an extra set handled by a shared/clients controller
      # the declaration is created from a form scoped to an exisiting client, so the form defaults to a patch (update request) (with nested attributes for  the new declaration)
      # so we only have an update route, not a create route
      # we cannot edit or destroy declarations through the UI
      resource :declaration, only: [:new, :show, :update] do
        resources :declaration_updates, except: [:index] 
      end
    end
    resources :declarations, only: [:index] do # we want an index of all declarations (not an index of each clients declarations)  
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
  end
end

app/models/strength_marker.rb
class StrengthMarker < ApplicationRecord
  belongs_to :client
  validates :date, presence: true
  validates :weight, presence: true, numericality: true  
  validates :reps, presence: true, numericality: true  
  validates :sets, presence: true, numericality: true

  scope :order_by_date, -> { order(date: :desc, name: :asc, weight: :asc) }
  scope :order_by_name, -> { order(name: :desc, date: :desc) }
  scope :order_by_weight, -> { order(weight: :desc, date: :desc) }
  # scope :with_client_id, ->(id) { joins(:client).where(client: {id: id})}
  scope :with_client_id, ->(id) { where(client_id: id)}
  scope :with_marker_name, ->(name) { where(name: name )}
end

app/controllers/shared/achievements_controller.rb
class Shared::AchievementsController < Shared::BaseController
  before_action :set_achievement, only: [:show, :edit, :update, :destroy]

  def index
    @achievements = Achievement.order_by_date
  end

  def new
    @achievement = Achievement.new
    set_options
  end

  def edit
    set_options
  end

  def create
    @achievement = Achievement.new(achievement_params)
    if @achievement.save
      flash_message :success, t('.success')
      redirect_to achievements_path
    else
      set_options
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @achievement.update(achievement_params)
      flash_message :success, t('.success')
      redirect_to achievements_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @achievement.destroy
    flash_message :success, t('.success')
    redirect_to achievements_path
  end

  private

  def set_achievement
    @achievement = Achievement.find(params[:id])
  end

  def set_options
    @challenges = Challenge.all
    @clients = Client.order_by_first_name
  end

  def achievement_params
    params.require(:achievement).permit(:date, :score, :challenge_id, :client_id)
  end
end

app/controllers/shared/base_controller.rb
class Shared::BaseController < ApplicationController
  layout :determine_layout
  before_action :admin_or_instructor_account
  before_action :set_public_timetable # for navigation bar
  before_action :set_admin_status

  private

  def determine_layout
    'admin'
  end

  def set_public_timetable
    # @current_timetable = Timetable.find(Rails.application.config_for(:constants)['display_timetable_id'])
    @current_timetable = Timetable.actives_at(Time.zone.now).first    
  end
end

app/controllers/shared/body_markers_controller.rb
class Shared::BodyMarkersController < Shared::BaseController
  skip_before_action :admin_or_instructor_account
  before_action :admin_or_instructor_or_client_account, only: [:index, :new, :filter]
  before_action :set_body_marker, only: [:edit, :update, :destroy]
  before_action :set_client
  before_action :correct_account_or_admin_or_instructor_account, only: [:edit, :create, :update, :destroy]  
  before_action :initialize_sort, only: :index  

  def index
      @body_markers =  @client_logging ?  @client.body_markers : BodyMarker.all.includes(:client)
      handle_client_filter unless @client_logging
      handle_marker_filter
      handle_sort
      @hide_chart = @body_markers.empty? || !@client_logging && session[:client_select] == 'All' ? true : false
      unless @hide_chart
        BodyMarker.default_timezone = :utc
        # HACK: hash returned has a key:value pair at each date, but the line_chart doesnt join dots when there are nil values in between, so remove nil values with #compact        
        @all_markers_grouped = @body_markers.unscope(:order)&.group(:bodypart)&.group_by_day(:date)&.average(:measurement)&.compact
        # hack to fix quirk of date format for column chart (but no good on line_chart, unintneded consequence that when dates are not all in same year, shown as year 2001..??)
        # https://github.com/ankane/chartkick/issues/352
        # @all_markers_grouped.transform_keys!{ |key| [key[0],key[1].strftime("%d %b")] }
        BodyMarker.default_timezone = :local
      end
      prepare_client_filter unless @client_logging
      prepare_marker_filter
      handle_pagination
      handle_index_response
  end

  def new
    @body_marker = BodyMarker.new
    set_options
    @form_cancel_link = body_markers_path
  end

  def edit
    set_options
    @form_cancel_link = body_markers_path
  end

  def create
    @body_marker = BodyMarker.new(body_marker_params)
    if @body_marker.save
      flash_message :success, t('.success')
      redirect_to body_markers_path
    else
      set_options
      @form_cancel_link = body_markers_path
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @body_marker.update(body_marker_params)
      flash_message :success, t('.success')
      redirect_to body_markers_path
    else
      set_options
      @form_cancel_link = body_markers_path
      render :edit, status: :unprocessable_entity
    end
  end  

  def destroy
    @body_marker.destroy
    flash_message :success, t('.success')
    redirect_to body_markers_path
  end
  
  def filter
    session[:body_marker_select] = params[:body_marker_select] || session[:body_marker_select] 
    unless @client_logging
      session[:client_select] = params[:client_select] || session[:client_select] 
    end
    redirect_to body_markers_path
  end  


  private

    def initialize_sort
      session[:body_marker_sort_option] = params[:body_marker_sort_option] || session[:body_marker_sort_option] || 'date'
    end

    def handle_sort
      @body_markers = @body_markers.send("order_by_#{session[:body_marker_sort_option]}")
    end

    def handle_pagination
      @pagy, @body_markers = pagy(@body_markers)
    end  

    def handle_client_filter
      return unless session[:client_select].present? && session[:client_select] != 'All'
  
      @body_markers = @body_markers.with_client_id(session[:client_select])
    end    

    def handle_marker_filter
      return unless session[:body_marker_select].present? && session[:body_marker_select] != 'All'
  
      @body_markers = @body_markers.with_marker_bodypart(session[:body_marker_select])
    end    

    def set_body_marker
      @body_marker = BodyMarker.find(params[:id])
    end

    def set_client
      return unless logged_in_as? 'client'

      @client = current_account.client
      @client_logging = true
    end

    def set_options
      (@client_options = Client.order_by_first_name) unless @client_logging
      @body_markers = Setting.body_markers.sort
    end

    def prepare_client_filter
      clients_with_body_markers = Client.has_body_marker.order_by_first_name.map { |c| [c.name, c.id] }
      @client_filters = ['All'] + clients_with_body_markers
    end

    def prepare_marker_filter
      if @client_logging
        @marker_filters = ['All'] + @client.body_markers.select(:bodypart).distinct.order(:bodypart).pluck(:bodypart)
      else
        @marker_filters = ['All'] + BodyMarker.select(:bodypart).distinct.order(:bodypart).pluck(:bodypart)
      end
    end

    def body_marker_params
      params.require(:body_marker).permit(:bodypart, :measurement, :date, :note, :client_id)
    end

    def correct_account_or_admin_or_instructor_account
      return if logged_in_as?('admin', 'superadmin', 'instructor')

      @client = if request.post? #create
                  Client.find(params.dig(:body_marker, :client_id).to_i)
                else # edit, update, destroy
                  @body_marker.client
                end
      return if current_account?(@client&.account)
  
      flash_message :warning, t('.warning')
      redirect_to login_path
    end
    
    
    def handle_index_response
      respond_to do |format|
        format.html
        format.turbo_stream
      end
    end    
end

app/views/shared/strength_markers/_filter_form.html.erb
<div id="strength_markers-filter" class="container px-1 my-3">
  <div class="container search">
    <% unless @client_logging %>
      <%= form_with(url: filter_strength_markers_path, method: "get", class: "form-class", data: {turbo_frame: "strength_markers"}) do %>
        <fieldset class="my-2">
          <label class='d-inline'>client:</label>
          <select name="client_select" class= "sort" onchange="this.form.requestSubmit()">
            <%= options_for_select @client_filters, session[:client_select] %>
          </select>
        </fieldset>
      <% end %>
    <% end %>
    <%= form_with(url: filter_strength_markers_path, method: "get", class: "form-class", data: {turbo_frame: "strength_markers"}) do %>
      <fieldset class="">
      <label class='d-inline'>marker:</label>
        <select name="strength_marker_select" class= "sort" onchange="this.form.requestSubmit()">
          <%= options_for_select @marker_filters, session[:strength_marker_select] %>
        </select>
      </fieldset>      
    <% end %>      

    <hr class = "my-2"></hr>    
    <%= render partial: 'sort_selection' %>
  </div>
  <hr class = "my-2"></hr>
</div>

app/views/shared/strength_markers/_form.html.erb
<%= form_with(model: strength_marker, class: 'admin_form pt-4 my-2') do |form| %>
  <% if strength_marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(strength_marker.errors.count, "error") %> prohibited this strength marker from being saved:</h2>

      <ul>
        <% strength_marker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @client_logging %>
    <%= form.hidden_field :client_id, value: @client.id %>
  <% else %>
    <div class="field">
      <%= form.label :client_id %>
      <%= form.collection_select :client_id, @client_options, :id, :name  %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.select :name, @strength_marker_options %>
  </div>

  <div class="field">
    <%= form.label :weight, 'Weight (kg)' %>
    <%= form.number_field :weight, step: 0.25, value: strength_marker.weight || 0, in: 0..300 %>
  </div>

  <div class="field">
    <%= form.label :reps %>
    <%= form.number_field :reps, in: 1..50 %>
  </div>

  <div class="field">
    <%= form.label :sets %>
    <%= form.number_field :sets, in: 1..20 %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <div class="cancel">
    <%= link_to image_tag('delete.png', class: "table_icon"), @form_cancel_link %>
  </div>      
<% end %>

app/views/shared/strength_markers/_sort_selection.html.erb
<form action="/strength_markers" method="GET">
  <div class="mt-0">
    <i class="fas fa-sort-alpha-down"></i>
    <select class="form-control-sm sort" name="strength_marker_sort_option" onchange="this.form.requestSubmit()">
      <option disabled="disabled" selected="selected" value="">Sort by</option>
      <option value="date" <%="selected" if session[:strength_marker_sort_option] == "date"%> >date</option>
      <option value="name" <%="selected" if session[:strength_marker_sort_option] == "name"%> >activity</option>
      <option value="weight" <%="selected" if session[:strength_marker_sort_option] == "weight"%> >weight</option>
    </select>
  </div>
</form>


app/views/shared/strength_markers/_strength_marker.html.erb
<% admin_plus = logged_in_as?('admin', 'superadmin') ? true : false %>
<%= turbo_frame_tag strength_marker do %>
  <div class="row">
    <div class="column col-1x"><%= strength_marker.date.strftime('%d %b %y') %></div>
    <div class="column col-1x"><%= strength_marker.name %></div>
    <div class="column col-1x"><%= number_with_precision(strength_marker.weight, precision: 2, strip_insignificant_zeros: true) %></div>
    <div class="column col-1x"><%= strength_marker.reps %></div>
    <div class="column col-1x"><%= strength_marker.sets %></div>
    <div class="column col-1x"><%= strength_marker.note %></div>
    <% unless @client %>
      <div class="column col-2x">
        <% if admin_plus %>
          <%= link_to strength_marker.client.name, client_path(strength_marker.client), class: 'like_button', data: {turbo: false} %>
        <% else %>
          <div class="column col-2x"><%= strength_marker.client.name %></div>
        <% end %>
      </div>
    <% end %>
    <div class="column nomobile"><%= link_to image_tag("edit.png", class: "table_icon"), edit_strength_marker_path(strength_marker) %></div>
    <div class="column nomobile"><%= link_to image_tag("delete.png", class: "table_icon"), strength_marker_path(strength_marker), data: {turbo_method: :delete, turbo_frame: "_top", turbo_confirm: 'Marker will be deleted. Are you sure?' } %></div>
  </div>
<% end %>

app/views/shared/strength_markers/_strength_markers_chart.html.erb
<div id="strength-markers-chart" class="container px-0 mb-5">
  <%= column_chart @all_markers_grouped, suffix: "kg" %>
</div>

app/views/shared/strength_markers/_strength_markers_table.html.erb
<div id="strength-markers-table" class="container px-0 mb-5">
  <div class="page_entries_info px-1">
      <div class="record-count mb-1">
        <%= "showing #{@strength_markers&.length} of #{@pagy&.count}" %>
      </div>
    <div data-controller="pagy-initializer">
      <%== pagy_bootstrap_combo_nav_js(@pagy) %>
    </div>   
  </div>
  <div class="admin-table mt-2">
    <div class="row fw-bolder">
      <div class="column col-1x">Date</div>
      <div class="column col-1x">Activity</div>
      <div class="column col-1x">Weight</div>
      <div class="column col-1x">Reps</div>
      <div class="column col-1x">Sets</div>
      <div class="column col-1x">Note</div>
      <% unless @client %>
        <div class="column col-2x">Client</div>
      <% end %>
      <div class="column nomobile"></div>
      <div class="column nomobile"></div>
    </div>
  </div>
  <div class="admin-table striped">
    <%= render @strength_markers %>
  </div>
</div>

app/views/shared/strength_markers/edit.html.erb
<%= turbo_frame_tag dom_id(@strength_marker) do %>
  <div class="container mb-4">  
    <%= render 'form', strength_marker: @strength_marker, class: 'mb-4' %>
  </div>
<% end %>

app/views/shared/strength_markers/index.html.erb
<div class="text-center mb-3 mb-md-0">
  <%= link_to 'strength', strength_markers_path, class:'option_choice current me-1' %>
  <%= link_to 'body', body_markers_path, class:'option_choice' %>
</div>

<div class="container px-1">
  <h4>Strength Markers <%= link_to image_tag('add.png', class: "button_icon"),
                                   new_strength_marker_path,
                                   data: { turbo_frame: dom_id(StrengthMarker.new) } %>
  </h4>
  <%= turbo_frame_tag StrengthMarker.new %>  
</div>
<%= turbo_frame_tag 'strength_markers' do %>
  <%= render partial: 'filter_form' %>
  <%# <%= render partial: 'strength_markers_chart' unless session[:client_select] == 'All' %>
  <%= render 'strength_markers_table' %>
<% end %>

app/views/shared/strength_markers/index.turbo_stream.erb
<%= turbo_stream.update "strength-markers-table" do %>
  <%= render partial: "strength_markers_table" %>
<% end %>
<%= turbo_stream.prepend "flash", partial: "partials/flashes" %>
<%= turbo_stream.remove "errors" %>

app/views/shared/strength_markers/new.html.erb
<%= turbo_frame_tag @strength_marker do %>
  <div class="col-md-6 mb-4">
    <%= render 'form', strength_marker: @strength_marker %>
  </div>
<% end %>