config/routes.rb
Rails.application.routes.draw do
  # https://stackoverflow.com/questions/65794152/how-can-i-do-a-health-check-for-a-rails-based-app-on-render
  get '/health_check', to: proc { [200, {}, ['success']] }
  # whereas below from railsguide3.13 doesnt work
  # get '/health', to: ->(env) { [204, {}, ['']] }

  scope module: :public_pages do
    root 'home#welcome'
    get '/about', to: 'footer#about'
    get '/terms_and_conditions', to: 'footer#package_policy'
    get '/charges_and_deductions', to: 'footer#charges'
    get '/privacy_policy',  to: 'footer#privacy_policy'
    get '/payment_policy',  to: 'footer#payment_policy'
    get '/contact',  to: 'footer#contact'
    get '/group_classes', to: 'home#group_classes'
    get '/signup', to: 'home#signup'
    post '/signup',  to: 'home#create_account'
    get '/chootiya', to: 'home#wedontsupport'
    get '/buboo', to: 'home#hearts'
  end

  # https://guides.rubyonrails.org/routing.html 2.10 Adding More RESTful Actions...2.10.2 Adding Collection Routes
  scope module: :admin do
    get '/wkclasses/instructor_select'
    get '/footfall', to: 'bookings#footfall'
    get '/timetable', to: 'timetables#public_format', as: 'public_format_timetable'
    post '/timetable/:id/copy', to: 'timetables#deep_copy', as: 'timetable_deep_copy'
    post '/wkclasses/:id/repeat', to: 'wkclasses#repeat', as: 'wkclass_repeat'
    resources :products, :wkclasses, :workouts do
      # get 'filter', on: :collection
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
    # Something to be aware of https://guides.rubyonrails.org/routing.html section 2.2
    # if say get 'admin/purchases/filter' was after the (admin namespaced) resources :purchases, a request to admin/purchases/filter would be handled by the show method
    # of the purchases controller (with params[:id] = 'filter') and an error would arise 'ActiveRecord::RecordNotFound (Couldn't find Purchase with 'id'=filter):'. 
    # the first match of the url 'admin/purchases/filter' would be /admin/purchases/:id(.:format), handled by the show method. The admin/purchases/filter(.:format) would be ignored as it comes later. 
    resources :purchases do
      collection do
        get 'clear_filters'
        get 'client_filter'
        get 'discount'
        get 'filter'
        get 'form_field_change'
        get 'analysis'
        patch ':id/expire', to: 'purchases#expire', as: 'expire'
      end
    end
    resources :clients do
      collection do
        get 'filter'
        get 'clear_filters'
        get 'analyze'        
      end
    end
    resources :freezes, except: [:show] do
      get 'filter', on: :collection
    end
    resources :workout_groups do
      collection do
        get ':id/instructor_expense_filter', to: 'workout_groups#instructor_expense_filter', as: 'instructor_expense_filter'
        get ':id/show_workouts', to: 'workout_groups#show_workouts', as: 'show_workouts'
        patch 'toggle_current/:id', to: 'workout_groups#toggle_current', as: 'toggle_current'
      end
    end
    resources :adjustments, :entries, :prices, except: [:index, :show]
    resources :accounts, only: [:create, :update, :destroy]
    resources :achievements, except: [:show]    
    # an update of a booking is handled by the booking cancellations controller (not the bookings controller)
    resources :bookings, only: [:new, :create, :destroy]
    resources :booking_cancellations, only: :update
    resources :fitternities, :instructors, :partners, :timetables
    resources :restarts, except: :show
    resources :table_times, :table_days, except: [:index, :show]
  end

  namespace :superadmin do
    resource :settings, only: [:show, :create]
  end
  
  # https://guides.rubyonrails.org/routing.html section 2.6 namespaces & routing
  # routes to a superadmin namespaced controller, but doesn't include superadmin in the url or url helper
  scope module: :superadmin do
    resources :announcements do
      collection do
        get 'add_client/:id', to: 'announcements#add_client', as: 'add_client'
        get ':id/remove_client/:client_id', to: 'announcements#remove_client', as: 'remove_client'
        get ':id/blast_off', to: 'announcements#blast_off', as: 'blast_off'
        get 'clear_filters/:id', to: 'announcements#clear_filters', as: 'clear_filters'
        get 'filter/:id', to: 'announcements#filter', as: 'filter_client'
        delete 'destroy_notification/:id', to: 'announcements#destroy_notification', as: 'destroy_notification'
      end
    end
    post 'orders', to: 'orders#create'
    post 'verify_payment', to: 'orders#verify_payment'
    post 'regular_expenses/add'
    namespace :charts do
      get 'purchase_count_by_week'
      get 'purchase_charge_by_week'
      # get 'purchase_count_by_wg/:year', to: '#purchase_count_by_wg', as: :purchase_count_by_wg
      get 'purchase_count_by_wg'
      get 'purchase_charge_by_wg'
      get 'product_group_count'
      get 'product_pt_count'
    end
    resource :blast, only: :show do
      collection do
        get 'add_client'
        get 'remove_client/:id', to: 'blasts#remove_client', as: 'remove_client'
        get 'blast_off'
        get 'clear_filters'
        get 'filter'
        get 'test'
        post 'add_message'
      end
    end
    resource :bulk_freeze, only: :show do
      collection do
        get 'remove_purchase/:id', to: 'bulk_freezes#remove_purchase', as: 'remove_purchase'
        get 'blast_off'
        get 'clear_filters'
        get 'filter'
        post 'process_details'        
      end
    end
    resources :discounts, :discount_reasons
    resources :employee_accounts do
      collection do
        get 'add_role/:id', to: 'employee_accounts#add_role', as: 'add_role'
        get 'remove_role/:id', to: 'employee_accounts#remove_role', as: 'remove_role'
        patch 'password_reset_of_employee/:id', to: 'employee_accounts#password_reset_of_employee', as: 'password_reset'
      end
    end
    resources :instructor_rates, :other_services, :regular_expenses, except: [:show]
    resources :payments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
    resources :expenses, except: :show do
      get 'filter', on: :collection
    end
  end

  scope module: :auth do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    get '/switch_account_role', to: 'sessions#switch_account_role'
    # hack to simulate closing a browser used only for integration testing (as sessions can't be directly amended in integration tests)
    get '/close_the_browser',  to: 'sessions#close_the_browser'
  end

  scope module: :client do
    get 'profile/:id', to: 'data_pages#profile', as: :client_profile
  end

  namespace :client do    
    get '/:id/notifications', to: 'data_pages#notifications', as: 'notifications'
    get '/:id/shop', to: 'dynamic_pages#shop', as: 'shop'
    get '/:id/history', to: 'data_pages#history', as: 'history'
    get ':id/bookings', to: 'bookings#index', as: 'bookings'
    post ':id/bookings', to: 'bookings#create', as: 'create_booking'
    # temporarily retain this route and redirect to client_bookings_path
    get '/:id/book', to: 'dynamic_pages#book', as: 'book'
    get '/:id/pt', to: 'data_pages#pt', as: 'pt'
    get '/timetable', to: 'data_pages#timetable', as: 'timetable'
    get '/:id/achievements', to: 'data_pages#achievements', as: 'achievements'
    get ':id/new_freeze', to: 'package_modification#new_freeze', as: 'package_modification_new_freeze'
    get ':id/restart', to: 'package_modification#restart', as: 'package_modification_restart'
    get ':id/transfer', to: 'package_modification#transfer', as: 'package_modification_transfer'
    get ':id/cancel_freeze', to: 'package_modification#cancel_freeze', as: 'package_modification_cancel_freeze'
    get ':id/cancel_restart', to: 'package_modification#cancel_restart', as: 'package_modification_cancel_restart'
    get ':id/cancel_transfer', to: 'package_modification#cancel_transfer', as: 'package_modification_cancel_transfer'
    post ':id/buy_freeze', to: 'package_modification#buy_freeze', as: 'buy_freeze'
    # test out on console $app.client_update_booking_path(Client.first, Client.first.bookings.last)
    # => "/client/1/booking_cancellations/1668"
    patch ':client_id/booking_cancellations/:id', to: 'booking_cancellations#update', as: 'update_booking' 
    resources :waitings, only: [:create, :destroy]
    resources :password_resets, only: [:new, :create, :edit, :update] do
      collection do
        # TODO: should be patch
        get 'password_change/:id', to: 'password_resets#password_change', as: 'password_change'
      end
    end
  end

  scope module: :shared do
    # resources :achievements, except: [:show]
    resources :body_markers, :strength_markers, except: [:show] do
      get 'filter', on: :collection
    end
    resources :challenges
    resources :client, only: [] do # already have the client resource routes in the admin module, dont want an extra set handled by a shared/clients controller
      # the declaration is created from a form scoped to an exisiting client, so the form defaults to a patch (update request) (with nested attributes for  the new declaration)
      # so we only have an update route, not a create route
      # we cannot edit or destroy declarations through the UI
      resource :declaration, only: [:new, :show, :update] do
        resources :declaration_updates, except: [:index] 
      end
    end
    resources :declarations, only: [:index] do # we want an index of all declarations (not an index of each clients declarations)  
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
  end
end

app/controllers/admin/timetables_controller.rb
class Admin::TimetablesController < Admin::BaseController
  skip_before_action :admin_account, only: [:show_public, :show]
  before_action :junioradmin_account, only: :show
  before_action :set_timetable, only: [:show, :edit, :update, :destroy, :deep_copy]
  before_action :set_active_timetables, only: :index

  def index
    @timetables = Timetable.order_by_date_until
    unique_current_timetable
  end

  def show
    # could build a entries hash to avoid database lookups in the view
    @days = @timetable.table_days.order_by_day
    @colspan = @days.size + 1
    @morning_times = @timetable.table_times.during('morning').order_by_time
    @afternoon_times = @timetable.table_times.during('afternoon').order_by_time
    @evening_times = @timetable.table_times.during('evening').order_by_time
    render layout: 'timetable'
  end

  def public_format
    @entries_hash = Timetable.display_entries(show_publicly_invisible: true)
    render 'public_pages/timetable', layout: 'public'
  end

  def new
    @timetable = Timetable.new
  end

  def edit; end

  def create
    @timetable = Timetable.new(timetable_params)
    if @timetable.save
      flash[:success] = t('.success')
      redirect_to timetable_path(@timetable)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @timetable.update(timetable_params)
      flash[:success] = t('.success')
      redirect_to timetables_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @timetable.destroy
    flash[:success] = t('.success')
    redirect_to timetables_path
  end

  def deep_copy
    #TODO: validate: false added as TableDay#no_repeated_days fails with validations. Don't see any problem with not running validations, but perhaps more robust to 
    # investigate more why this happens and perhaps solve by adding return nil if inputs are nil to for_day_of_week method  
    t_copy = @timetable.deep_clone include: [ {table_days: :entries}, { table_times: :entries} ], use_dictionary: true, validate: false
    t_copy.update(title: "#{t_copy.title} (copy)") # NOTE: update saves record
    flash[:success] = t('.success')
    redirect_to timetables_path    
  end

  private

  def set_active_timetables
    @active_display = Timetable.actives_at(Time.zone.now).first
    wkclass_date = Time.zone.now.advance(days: Rails.application.config_for(:constants)['wkclassmaker_advance'])
    @active_build = Timetable.actives_at(wkclass_date).first
  end

  def unique_current_timetable
    case Timetable.current_at(Time.zone.now).size
    when 0 
      @uniqueness_error = true
      @uniqueness_error_message = "There is no timetable active at today's date."
    when 1
      @uniqueness_error = false
    else
      @uniqueness_error = true
      @uniqueness_error_message = "There is more than 1 timetable current at today's date."
    end
  end

  def set_timetable
    @timetable = Timetable.find(params[:id])
  end

  def timetable_params
    params.require(:timetable).permit(:title, :date_from, :date_until)
  end
end

app/views/admin/timetables/_form.html.erb
<%= form_with(model: timetable) do |form| %>
  <% if timetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timetable.errors.count, "error") %> prohibited this timetable from being saved:</h2>

      <ul>
        <% timetable.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field mb-3">
    <%= form.label :date_from, 'starting on' %>
    <%= form.date_field :date_from, value: (form.object.new_record? ? Date.today : form.object.date_from) %>
  </div>
  
  <div class="field mb-3">
    <%= form.label :date_until, 'ending on' %>
    <%= form.date_field :date_until, value: (form.object.new_record? ? 1.years.from_now.to_date : form.object.date_until) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/timetables/_time_period_table_body.html.erb
<tr>
  <th><%=time.start.strftime("%l.%M")%>
    <div class = "editButton">
      <%= link_to image_tag('edit.png', class: "table_icon"), edit_table_time_path(time) %>
      <%= link_to image_tag('delete.png', class: "table_icon"), table_time_path(time), data: { turbo_method: :delete, turbo_confirm: 'This will delete the timetable row and all the entries for that time. Are you sure?' } %>
    </div>
  </th>
  <% @days.each do |day| %>
    <td>
      <% entry = Entry.where(table_time_id: time.id, table_day_id: day.id).first %>
        <div class="workout-name" data-toggle="tooltip" title=<%="#{time.start.strftime("%l.%M")}-#{day.name}"%> ><%=entry&.workout&.name%></div>
        <div class="bodypart"><%=entry&.goal%></div>
        <div class="studio mt-1"><%=entry&.level%></div>
        <div class="studio mt-1"><%=entry&.studio%></div>
      <div class = "editButton">
        <% if entry.nil? %>
          <%= link_to image_tag('add.png', class: "table_icon"), new_entry_path(timetable_id: params[:id], table_day_id: day.id, table_time_id: time.id) %>
        <% else %>
        <%= link_to image_tag('edit.png', class: "table_icon"), edit_entry_path(entry) %>
        <%= link_to image_tag('delete.png', class: "table_icon"), entry_path(entry), data: { turbo_method: :delete, confirm: 'Are you sure?' } %>
      <% end %>
      </div>
    </td>
  <% end %>
</tr>

app/views/admin/timetables/_timetable.html.erb
<% timetable_decorator = decorate(timetable) %>
<% use_for_display = timetable == @active_display %>
<% use_for_wkclass = timetable == @active_build %>
<div class="row">
  <div class="column col-1x"><%= timetable_decorator.title_link %></div>
  <div class="column col-1x"><%= timetable_decorator.date_fromm %></div>
  <div class="column col-1x"><%= timetable_decorator.date_untill %></div>
  <div class="column"><%= timetable_decorator.display(use_for_display) %></div>
  <div class="column"><%= timetable_decorator.wkclass_maker(use_for_wkclass) %></div>
  <div class="column"><%= timetable_decorator.edit %></div>
  <div class="column"><%= timetable_decorator.delete %></div>
  <div class="column"><%= timetable_decorator.copy %></div>
</div>

app/views/admin/timetables/_timetables_table.html.erb
<div id="timetable-table" class="container px-0 mb-5">
  <div class="admin-table striped">
    <%= render @timetables %>
  </div>
</div>

app/views/admin/timetables/edit.html.erb
<h4>Edit Timetable</h4>
<%= render 'form', timetable: @timetable %>
<%= link_to 'Back', timetables_path %>

app/views/admin/timetables/index.html.erb
<div class="container px-1">
  <% if @uniqueness_error %>
    <div class="alert alert-danger"><%= @uniqueness_error_message %></div>
  <% end %>
  <h4> Timetables <%= link_to image_tag('add.png', class: "button_icon"), new_timetable_path %></h4>
</div>
<%= render partial: 'timetables_table' %>

app/views/admin/timetables/new.html.erb
<h4>New Timetable</h4>
<%= render 'form', timetable: @timetable %>
<%= link_to 'Back', timetables_path %>

app/views/admin/timetables/show.html.erb
<div class="container">
  <div class="positioning-wrap">
    <div class="mb-3"><h4><%= @timetable.title %> <small></small></div></h4>
    <div class="GeneralText mb-2" data-controller="timetable-builder" data-timetable-builder-cssclass-value="editButton" data-timetable-builder-display-value="block">
      <%= button_tag 'Preview...', id: "btnPreview", class:'btn btn-black', data: {action: "timetable-builder#toggle_visibility"} %>
    </div>
  </div>

  <p class="GeneralText mb-1 mb-2">All classes are 60mins unless stated otherwise.</p>

  <table class="timetable">
    <thead>
      <tr style="background-color:white;">
        <th>
          <div class = "editButton">
            <%= link_to image_tag('add.png', class: "table_icon"), new_table_time_path(timetable_id: params[:id]) %>time
          </div>
          <div class = "editButton">
            <%= link_to image_tag('add.png', class: "table_icon"), new_table_day_path(timetable_id: params[:id]) %>day
          </div>
        </th>
        <% @days.each do |day| %>
          <th class= "large-screen" style="text-align:center; text-transform: uppercase;">
            <%=day.name%>
            <div class = "editButton">
              <%= link_to image_tag('edit.png', class: "table_icon"), edit_table_day_path(day) %>
              <%= link_to image_tag('delete.png', class: "table_icon"), table_day_path(day), data: { turbo_method: :delete, turbo_confirm: "This will delete the timetable day and all the day's entries. Are you sure?" } %>
            </div>    
          </th>
          <th class= "small-screen" style="text-align:center;"><%=day.short_name%></th>
        <%end%>
      </tr>
    </thead>

    <% unless @morning_times.empty? %>
      <tr style="background:linear-gradient(white,#dddddd)">
        <th colspan=<%= @colspan %>>MORNING</th>
      </tr>
      <% @morning_times.each do |time| %>
        <%= render 'time_period_table_body', time: time %>
      <% end %>
    <% end %>

    <% unless @afternoon_times.empty? %>
      <tr style="background:linear-gradient(white,#dddddd)">
        <th colspan=<%= @colspan %>>AFTERNOON</th>
      </tr>
      <% @afternoon_times.each do |time| %>
        <%= render 'time_period_table_body', time: time %>
      <% end %>  
    <% end %>  

    <% unless @evening_times.empty? %>
      <tr style="background:linear-gradient(white,#dddddd)">
        <th colspan=<%= @colspan %>>EVENING</th>
      </tr>
      <% @evening_times.each do |time| %>
        <%= render 'time_period_table_body', time: time %>
      <% end %>
    <% end %>    

  </table>
</div>