config/routes.rb
Rails.application.routes.draw do
  # https://stackoverflow.com/questions/65794152/how-can-i-do-a-health-check-for-a-rails-based-app-on-render
  get '/health_check', to: proc { [200, {}, ['success']] }
  # whereas below from railsguide3.13 doesnt work
  # get '/health', to: ->(env) { [204, {}, ['']] }

  scope module: :public_pages do
    root 'home#welcome'
    get '/about', to: 'footer#about'
    get '/terms_and_conditions', to: 'footer#package_policy'
    get '/charges_and_deductions', to: 'footer#charges'
    get '/privacy_policy',  to: 'footer#privacy_policy'
    get '/payment_policy',  to: 'footer#payment_policy'
    get '/contact',  to: 'footer#contact'
    get '/group_classes', to: 'home#group_classes'
    get '/signup', to: 'home#signup'
    post '/signup',  to: 'home#create_account'
    get '/chootiya', to: 'home#wedontsupport'
    get '/buboo', to: 'home#hearts'
  end

  # https://guides.rubyonrails.org/routing.html 2.10 Adding More RESTful Actions...2.10.2 Adding Collection Routes
  scope module: :admin do
    get '/wkclasses/instructor_select'
    get '/footfall', to: 'bookings#footfall'
    get '/timetable', to: 'timetables#public_format', as: 'public_format_timetable'
    post '/timetable/:id/copy', to: 'timetables#deep_copy', as: 'timetable_deep_copy'
    post '/wkclasses/:id/repeat', to: 'wkclasses#repeat', as: 'wkclass_repeat'
    resources :products, :wkclasses, :workouts do
      # get 'filter', on: :collection
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
    # Something to be aware of https://guides.rubyonrails.org/routing.html section 2.2
    # if say get 'admin/purchases/filter' was after the (admin namespaced) resources :purchases, a request to admin/purchases/filter would be handled by the show method
    # of the purchases controller (with params[:id] = 'filter') and an error would arise 'ActiveRecord::RecordNotFound (Couldn't find Purchase with 'id'=filter):'. 
    # the first match of the url 'admin/purchases/filter' would be /admin/purchases/:id(.:format), handled by the show method. The admin/purchases/filter(.:format) would be ignored as it comes later. 
    resources :purchases do
      collection do
        get 'clear_filters'
        get 'client_filter'
        get 'discount'
        get 'filter'
        get 'form_field_change'
        get 'analysis'
        patch ':id/expire', to: 'purchases#expire', as: 'expire'
      end
    end
    resources :clients do
      collection do
        get 'filter'
        get 'clear_filters'
        get 'analyze'        
      end
    end
    resources :freezes, except: [:show] do
      get 'filter', on: :collection
    end
    resources :workout_groups do
      collection do
        get ':id/instructor_expense_filter', to: 'workout_groups#instructor_expense_filter', as: 'instructor_expense_filter'
        get ':id/show_workouts', to: 'workout_groups#show_workouts', as: 'show_workouts'
        patch 'toggle_current/:id', to: 'workout_groups#toggle_current', as: 'toggle_current'
      end
    end
    resources :adjustments, :entries, :prices, except: [:index, :show]
    resources :accounts, only: [:create, :update, :destroy]
    resources :achievements, except: [:show]    
    # an update of a booking is handled by the booking cancellations controller (not the bookings controller)
    resources :bookings, only: [:new, :create, :destroy]
    resources :booking_cancellations, only: :update
    resources :fitternities, :instructors, :partners, :timetables
    resources :restarts, except: :show
    resources :table_times, :table_days, except: [:index, :show]
  end

  namespace :superadmin do
    resource :settings, only: [:show, :create]
  end
  
  # https://guides.rubyonrails.org/routing.html section 2.6 namespaces & routing
  # routes to a superadmin namespaced controller, but doesn't include superadmin in the url or url helper
  scope module: :superadmin do
    resources :announcements do
      collection do
        get 'add_client/:id', to: 'announcements#add_client', as: 'add_client'
        get ':id/remove_client/:client_id', to: 'announcements#remove_client', as: 'remove_client'
        get ':id/blast_off', to: 'announcements#blast_off', as: 'blast_off'
        get 'clear_filters/:id', to: 'announcements#clear_filters', as: 'clear_filters'
        get 'filter/:id', to: 'announcements#filter', as: 'filter_client'
        delete 'destroy_notification/:id', to: 'announcements#destroy_notification', as: 'destroy_notification'
      end
    end
    post 'orders', to: 'orders#create'
    post 'verify_payment', to: 'orders#verify_payment'
    post 'regular_expenses/add'
    namespace :charts do
      get 'purchase_count_by_week'
      get 'purchase_charge_by_week'
      # get 'purchase_count_by_wg/:year', to: '#purchase_count_by_wg', as: :purchase_count_by_wg
      get 'purchase_count_by_wg'
      get 'purchase_charge_by_wg'
      get 'product_group_count'
      get 'product_pt_count'
    end
    resource :blast, only: :show do
      collection do
        get 'add_client'
        get 'remove_client/:id', to: 'blasts#remove_client', as: 'remove_client'
        get 'blast_off'
        get 'clear_filters'
        get 'filter'
        get 'test'
        post 'add_message'
      end
    end
    resource :bulk_freeze, only: :show do
      collection do
        get 'remove_purchase/:id', to: 'bulk_freezes#remove_purchase', as: 'remove_purchase'
        get 'blast_off'
        get 'clear_filters'
        get 'filter'
        post 'process_details'        
      end
    end
    resources :discounts, :discount_reasons
    resources :employee_accounts do
      collection do
        get 'add_role/:id', to: 'employee_accounts#add_role', as: 'add_role'
        get 'remove_role/:id', to: 'employee_accounts#remove_role', as: 'remove_role'
        patch 'password_reset_of_employee/:id', to: 'employee_accounts#password_reset_of_employee', as: 'password_reset'
      end
    end
    resources :instructor_rates, :other_services, :regular_expenses, except: [:show]
    resources :payments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
    resources :expenses, except: :show do
      get 'filter', on: :collection
    end
  end

  scope module: :auth do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    get '/switch_account_role', to: 'sessions#switch_account_role'
    # hack to simulate closing a browser used only for integration testing (as sessions can't be directly amended in integration tests)
    get '/close_the_browser',  to: 'sessions#close_the_browser'
  end

  scope module: :client do
    get 'profile/:id', to: 'data_pages#profile', as: :client_profile
  end

  namespace :client do    
    get '/:id/notifications', to: 'data_pages#notifications', as: 'notifications'
    get '/:id/shop', to: 'dynamic_pages#shop', as: 'shop'
    get '/:id/history', to: 'data_pages#history', as: 'history'
    get ':id/bookings', to: 'bookings#index', as: 'bookings'
    post ':id/bookings', to: 'bookings#create', as: 'create_booking'
    # temporarily retain this route and redirect to client_bookings_path
    get '/:id/book', to: 'dynamic_pages#book', as: 'book'
    get '/:id/pt', to: 'data_pages#pt', as: 'pt'
    get '/timetable', to: 'data_pages#timetable', as: 'timetable'
    get '/:id/achievements', to: 'data_pages#achievements', as: 'achievements'
    get ':id/new_freeze', to: 'package_modification#new_freeze', as: 'package_modification_new_freeze'
    get ':id/restart', to: 'package_modification#restart', as: 'package_modification_restart'
    get ':id/transfer', to: 'package_modification#transfer', as: 'package_modification_transfer'
    get ':id/cancel_freeze', to: 'package_modification#cancel_freeze', as: 'package_modification_cancel_freeze'
    get ':id/cancel_restart', to: 'package_modification#cancel_restart', as: 'package_modification_cancel_restart'
    get ':id/cancel_transfer', to: 'package_modification#cancel_transfer', as: 'package_modification_cancel_transfer'
    post ':id/buy_freeze', to: 'package_modification#buy_freeze', as: 'buy_freeze'
    # test out on console $app.client_update_booking_path(Client.first, Client.first.bookings.last)
    # => "/client/1/booking_cancellations/1668"
    patch ':client_id/booking_cancellations/:id', to: 'booking_cancellations#update', as: 'update_booking' 
    resources :waitings, only: [:create, :destroy]
    resources :password_resets, only: [:new, :create, :edit, :update] do
      collection do
        # TODO: should be patch
        get 'password_change/:id', to: 'password_resets#password_change', as: 'password_change'
      end
    end
  end

  scope module: :shared do
    # resources :achievements, except: [:show]
    resources :body_markers, :strength_markers, except: [:show] do
      get 'filter', on: :collection
    end
    resources :challenges
    resources :client, only: [] do # already have the client resource routes in the admin module, dont want an extra set handled by a shared/clients controller
      # the declaration is created from a form scoped to an exisiting client, so the form defaults to a patch (update request) (with nested attributes for  the new declaration)
      # so we only have an update route, not a create route
      # we cannot edit or destroy declarations through the UI
      resource :declaration, only: [:new, :show, :update] do
        resources :declaration_updates, except: [:index] 
      end
    end
    resources :declarations, only: [:index] do # we want an index of all declarations (not an index of each clients declarations)  
      collection do
        get 'filter'
        get 'clear_filters'
      end
    end
  end
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  include WhatsappNumber
  has_many :wkclasses, dependent: nil
  has_many :instructor_rates, dependent: :destroy
  belongs_to :account, optional: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name, uniqueness: { scope: :last_name, message: 'Already an instructor with this name' }
  scope :order_by_name, -> { order(:first_name, :last_name) }
  scope :order_by_current, -> { order(current: :desc) }
  scope :current, -> { where(current: true) }
  scope :not_current, -> { where.not(current: true) }
  scope :has_rate, -> { joins(:instructor_rates).distinct }
  # scope :group_rates, -> { joins(:instructor_rates).where(instructor_rates: { group: true }) }
  # scope :pt_rates, -> { joins(:instructor_rates).where(instructor_rates: { group: false }) }
  with_options if: :whatsapp_raw do
    phony_normalize :whatsapp_raw, as: :whatsapp, default_country_code: :whatsapp_country_code
  end

  validates :whatsapp, phony_plausible: true

  attr_accessor :whatsapp_country_code, :whatsapp_raw

  def name
    "#{first_name} #{last_name}"
  end

  def current_rate
    instructor_rates.current.order_recent_first.first&.rate
  end

  def group_rates
    instructor_rates.where(group: true)
  end

  def pt_rates
    instructor_rates.where(group: false)
  end

  def initials
    name.split.map(&:first).join
  end

  # make dry same code used in client method
  def country_code(number = :whatsapp)
    return '+91' unless Phony.plausible?(send(number))

    "+#{PhonyRails.country_code_from_number(send(number))}"
  end

  def country(number = :phone)
    stored_number = send(number)
    return 'IN' unless Phony.plausible?(stored_number)

    # A bunch of countries use +1 like AG, VI etc...
    return 'US' if send(:country_code, number) == '+1'

    PhonyRails.country_from_number(stored_number)
  end

  def number_raw(number = :phone)
    stored_number = send(number)
    return stored_number unless Phony.plausible?(stored_number)

    stored_number.gsub(send(:country_code, number), '')
  end
end

app/controllers/admin/instructors_controller.rb
class Admin::InstructorsController < Admin::BaseController
  skip_before_action :admin_account, only: :show
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]
  before_action :correct_instructor_or_superadmin, only: :show
  before_action :initialize_sort, only: :show
  before_action :set_raw_numbers, only: :edit

  def index
    @current_instructors = Instructor.current.order_by_name.includes(:wkclasses, :account)
    @not_current_instructors = Instructor.not_current.order_by_name.includes(:wkclasses, :account)
    @superadmin = logged_in_as?('superadmin') ? true : false
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show
    set_period
    @wkclasses = Wkclass.during(@period).with_instructor(@instructor.id)
    @wkclasses_with_instructor_expense = @wkclasses.unscope(:order).has_instructor_cost.includes(:workout, :bookings, instructor: [:instructor_rates])
    @wkclasses_with_no_instructor_expense = @wkclasses.unscope(:order).has_no_instructor_cost.includes(:workout, :bookings, instructor: [:instructor_rates])
    # this double counts and I cant find a way to prevent it (tried with distinct and group) so fallen back on ruby object
    # @total_instructor_cost_for_period = @wkclasses_with_instructor_expense.sum(:rate)
    @total_instructor_cost_for_period = @wkclasses_with_instructor_expense.map(&:rate).inject(0, :+)
    handle_sort
    @months = months_logged
    @show_classes_with_no_expense = logged_in_as?('superadmin') ? true : false
  end

  def new
    @instructor = Instructor.new
  end

  def edit; end

  def create
    @instructor = Instructor.new(instructor_params)

    if @instructor.save
      redirect_to instructors_path
      flash[:success] = t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @instructor.update(instructor_params)
      redirect_to instructors_path
      flash[:success] = t('.success')
      # Once an instructor is retired, their rates should be too. False means image link clicekd, 0 meand edited by form
      retire_instructors_rates if ['false', '0'].include? instructor_params[:current]
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @instructor.destroy
    redirect_to instructors_path
    flash[:success] = t('.success')
  end

  private

  def retire_instructors_rates
    current_instructor_rates = @instructor.instructor_rates.current
    flash[:warning] = t('.instructor_rates_updated') unless current_instructor_rates.empty?
    current_instructor_rates.update_all(current: false)
  end

  def initialize_sort
    session[:instructor_expense_sort_option] = params[:instructor_expense_sort_option] || session[:instructor_expense_sort_option] || 'wkclass_date'
  end

  def handle_sort
    case session[:instructor_expense_sort_option]
    when 'wkclass_date'
      @wkclasses_with_instructor_expense = @wkclasses_with_instructor_expense.order_by_date
      @wkclasses_with_no_instructor_expense = @wkclasses_with_no_instructor_expense.order_by_date
    when 'client_name'
      sort_on_object
    end
  end

  def sort_on_object
    @wkclasses_with_instructor_expense = @wkclasses_with_instructor_expense.to_a.sort_by do |w|
      # this seems to be the way to use sort_by with a secondary order (but fails when booking is nil for some reason "|| 'Z'" mitigates this)
      [w.bookings&.first&.client&.name || 'Z', -w.start_time.to_i]
    end
    @wkclasses_with_no_instructor_expense = @wkclasses_with_no_instructor_expense.to_a.sort_by do |w|
      [w.bookings&.first&.client&.name || 'Z', -w.start_time.to_i]
    end
  end

  def set_period
    default_month = Time.zone.today.beginning_of_month.strftime('%b %Y')
    session[:revenue_month] = params[:revenue_month] || session[:revenue_month] || default_month
    session[:revenue_month] = default_month if session[:revenue_month] == 'All'
    @period = month_period(session[:revenue_month])
  end

  def set_instructor
    @instructor = Instructor.find(params[:id])
  end

  def correct_instructor_or_superadmin
    return if logged_in_as?('superadmin')

    redirect_to login_path unless current_account?(@instructor.account)
  end

  def set_raw_numbers
    @instructor.whatsapp_country_code = @instructor.country(:whatsapp)
    @instructor.whatsapp_raw = @instructor.number_raw(:whatsapp)
  end

  def instructor_params
    # the update method (and therefore the instructor_params method) is used through a form but also clicking on a link on the instructors page
    return { current: params[:current] } if params[:current].present?

    return { commission: params[:commission] } if params[:commission].present?
    
    return { employee: params[:employee] } if params[:employee].present?

    params.require(:instructor).permit(:first_name, :last_name, :email, :whatsapp_country_code, :whatsapp_raw, :current, :commission, :employee)
  end
end

app/views/admin/instructors/_form.html.erb
<%= form_with(model: instructor) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>
      <ul>
        <% instructor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :whatsapp_raw, 'Whatsapp' %>
    <div class="d-flex field">
      <%= form.country_select(:whatsapp_country_code, {priority_countries: ["IN", "US", "GB"], sort_provided: false, format: :with_data_attrs}, {class: ' me-2'} ) %>
      <%= form.text_field :whatsapp_raw, class: 'form-control' %>
    </div>
  </div>  

  <div class="field mb-3">
    <%= form.label :current do %>
      <%= form.check_box :current, { checked: @instructor.new_record? || form.object.current? } %>
      Current
    <% end %>
  </div>

  <div class="field mb-3">
    <%= form.label :commission do %>
      <%= form.check_box :commission, { checked: @instructor.new_record? || form.object.commission? } %>
      Commission
    <% end %>
  </div>

  <div class="field mb-3">
    <%= form.label :employee do %>
      <%= form.check_box :employee, { checked: @instructor.new_record? || form.object.employee? } %>
      Employee
    <% end %>
  </div>  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/instructors/_instructor.html.erb
<div class="row">
  <%= content_tag(:div, class: ["column col-1x",("fw-light" unless instructor.current?)].compact.join(' ')) do %>
    <% if @superadmin %>
      <%= link_to instructor.name, instructor_path(instructor), class: 'like_button', data: {turbo: false}%>
    <% else %>
      <%= instructor.name %>
    <% end %>            
  <% end %>            
  <% if logged_in_as?('superadmin') %>
    <div class="column col-0.5x"><%= instructor.wkclasses.size %></div>
  <% end %>            
  <div class="column col-1x nomobile"><%= instructor.email %></div>
  <div class="column col-1x"><%= number(instructor.whatsapp, instructor.whatsapp) %></div>        
  <div class="column"><%= link_to image_tag('bookings.png', class: ["table_icon",("greyed-out" unless instructor.current?)].compact.join(' ')), instructor_path(instructor, current: !instructor.current?), data: {turbo_method: :patch} %></div>
  <div class="column" data-toggle="tooltip" data-placement="top" title="commission: the instructor can see a log of classes on their dashboard for which they receive a payment">
    <%= link_to image_tag('commission.png', class: ["table_icon",("greyed-out" unless instructor.commission?)].compact.join(' ')), instructor_path(instructor, commission: !instructor.commission?), data: {turbo_method: :patch} %>
  </div>
  <div class="column" data-toggle="tooltip" data-placement="top" title="employee: the instructor can see the group classes log and update bookings">
    <%= link_to image_tag('employee.png', class: ["table_icon",("greyed-out" unless instructor.employee?)].compact.join(' ')), instructor_path(instructor, employee: !instructor.employee?), data: {turbo_method: :patch} %>
  </div>
  <div class="column"><%= link_to image_tag('edit.png', class: "table_icon"), edit_instructor_path(instructor), data: {turbo: false} %></div>
  <% if logged_in_as?('superadmin') %>   
    <div class="column" data-toggle="tooltip" data-placement="top" title="Create an account for this instructor. They will be sent a whatsapp with password.">
      <% if instructor.account.nil? && instructor.current? && !instructor.no_instructor %>
        <%= link_to image_tag('add.png', class: "table_icon"), employee_accounts_path(email: instructor.email, id: instructor.id, role_id: Role.find_by(name: 'instructor').id, link_from: 'instructors_index'), data: {turbo_method: :post, confirm: 'An account for this instructor will be created. Are you sure?' }  %>
      <% end %>
    </div>
  <% end %>   
</div>


app/views/admin/instructors/_instructors_table.html.erb
<div id="instructors-table" class="container px-0 mb-5">
  <div class="text-uppercase fst-italic">Current<small><%= "(#{@current_instructors.size})" %> </small></div>
  <div class="admin-table striped mt-2">
    <%= render @current_instructors, as: :instructor %>
  </div>
  <div class="text-uppercase fst-italic mt-3">Not Current<small><%= "(#{@not_current_instructors.size})" %> </small></div> 
  <div class="admin-table striped mt-2">    
    <%= render @not_current_instructors, as: :instructor %>
  </div>
</div>

app/views/admin/instructors/_sort_months.html.erb
<form action=<%= instructor_path(@instructor) %> method="GET">
  <select name="revenue_month" onchange="this.form.requestSubmit()" class= "sort">
    <%= options_for_select @months, session[:revenue_month] %>
  </select>
</form>

app/views/admin/instructors/_sort_options.html.erb
<form action=<%= instructor_path(@instructor) %> method="GET" data-remote="true" class="d-inline-block mt-2">
  <div class="ms-3">
    <i class="fas fa-sort-alpha-down"></i>
    <select class="form-control-sm sort" name="instructor_expense_sort_option" onchange="this.form.requestSubmit()">
      <option disabled="disabled" selected="selected" value="">Sort by</option>
      <option value="wkclass_date" <%="selected" if session[:instructor_expense_sort_option] == "wkclass_date"%> >class date</option>
      <option value="client_name" <%="selected" if session[:instructor_expense_sort_option] == "client_name"%> >client</option>
    </select>
  </div>
</form>

app/views/admin/instructors/_wkclasses_no_instructor_expense.html.erb
<div class="container px-0 mt-3">
  <h6 class="px-1 mb-1">Classes (with no additional payment)</h6>
  <% if @wkclasses_with_no_instructor_expense.empty? %>
    <p class= "fst-italic px-1">None</p>
  <% else %>
    <div class="admin-table striped">
      <% @wkclasses_with_no_instructor_expense.each_with_index do |wkclass, index| %>
        <% wkclass_decorator = decorate(wkclass) %>                  
        <div class="row">
          <div class="column"><%= index + 1 %></div>
          <div class="column col-2x"><%= wkclass_decorator.summary %></div>
          <div class="column col-2x"><%= wkclass_decorator.pt_client_name %></div>
          <div class="column col-2x"><%= wkclass_decorator.pt_status %></div>
          <div class="column col-2x"><%= wkclass_decorator.rate_formatted %></div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/admin/instructors/_wkclasses_with_instructor_expense.html.erb
<div class="container px-0 mt-2">
  <h6 class="px-1 mb-1">Classes (with additional payment)</h6>
  <% if @wkclasses_with_instructor_expense.empty? %>
    <p class= "fst-italic px-1">None</p>
  <% else %>
    <div class="admin-table striped">
      <% @wkclasses_with_instructor_expense.each_with_index do |wkclass, index| %>
        <% wkclass_decorator = decorate(wkclass) %>  
        <div class="row">
          <div class="column"><%= index + 1 %></div>
          <div class="column col-2x"><%= wkclass_decorator.summary %></div>
          <div class="column col-2x"><%= wkclass_decorator.pt_client_name %></div>
          <div class="column col-2x"><%= wkclass_decorator.pt_status %></div>
          <div class="column col-2x"><%= wkclass_decorator.rate_formatted %></div>
        </div>
      <% end %>
        <div class="row">
          <div class="column">Total</div>
          <div class="column col-1x"><%= rupees(@total_instructor_cost_for_period) %></div>
        </div>   
    </div>
  <% end %>
</div>

app/views/admin/instructors/edit.html.erb
<h4>Editing Instructor</h4>
<%= render 'form', instructor: @instructor %>
<%= link_to 'back to instructors', instructors_path %>

app/views/admin/instructors/index.html.erb
<div class="container px-1 mb-1">
  <h4>Instructors <%= link_to image_tag('add.png', class: "button_icon"), new_instructor_path %></h4>
</div>
<%= turbo_frame_tag 'instructors' do %>
  <%= render 'instructors_table' %>
<% end %>

app/views/admin/instructors/index.turbo_stream.erb
<%= turbo_stream.update "instructors" do %>
  <%= render partial: "instructors_table" %>
<% end %>
<%= turbo_stream.prepend "flash", partial: "partials/flashes" %>

app/views/admin/instructors/new.html.erb
<div class="col-md-6">
  <h4>New Instructor</h4>
  <%= render 'form', instructor: @instructor %>
  <%= link_to 'back to instructors', instructors_path %>
</div>

app/views/admin/instructors/show.html.erb
<%= turbo_frame_tag 'commissions' do %>
  <div class="container px-1">
    <h4><%="Instructor #{@instructor.name}" %></h4>
    <%= render 'sort_months' %> 
    <%= render 'sort_options' %>
  </div>
  <%= render 'wkclasses_with_instructor_expense' %>
  <%= render 'wkclasses_no_instructor_expense' %>
<% end %>